"""Functions for working with the solutions from opsolver."""
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Solution:
    """Class for storing information about a solution."""

    score: int
    number_of_controls: int
    distance: int
    distance_limit: int
    controls: list[int]


def get_solution(solution_file: Path) -> Solution:
    """Check and extract information from the solution generated by opsolver."""
    with open(solution_file) as file:
        last_line = file.readlines()[-1]
    last_sol = json.loads(last_line)

    return Solution(
        last_sol["sol"]["val"],
        last_sol["sol"]["sol_ns"],
        last_sol["sol"]["cap"],
        last_sol["prob"]["d0"],
        last_sol["sol"]["cycle"],
    )
